### ISSUE TITLE
[QST] Using  conv2d ElementOutput of int32_t

### ISSUE THREAD

**Issue by nolyn** [NVIDIA/cutlass#499]
Hi, I made these changes to the example 09_turing_tensorop_conv2dfprop:
[09_turing_tensorop_conv2dfprop_diff.txt](https://github.com/NVIDIA/cutlass/files/8715701/09_turing_tensorop_conv2dfprop_diff.txt)
 
It should change the example to perform convolution of int8_t with int8_t and have int32_t as output. I could run this on cutlass tag v2.8.0, but it does not work on the current master or v2.9.0.  I believe this worked as expected before. Is it a bug or was it a bug that it worked before? Or do I need to make more changes with cutlass >2.8.0?

Reason it fails to compiles is in default_epilogue_tensor_op.h:
```
[build] ../include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h(224): error: static assertion failed with "ElementsPerAccess needs to be 16 or 8."
[build]           detected during:
```

```
struct DefaultIteratorsTensorOp<
  ElementOutput, 
  int32_t, 
  ElementsPerAccess,
  ThreadblockShape, 
  WarpShape, 
  InstructionShape, 
  ThreadMap> {

  static_assert(cutlass::platform::is_same<ElementOutput, cutlass::int4b_t>::value ||
                cutlass::platform::is_same<ElementOutput, cutlass::uint4b_t>::value ||
                cutlass::platform::is_same<ElementOutput, int8_t>::value ||
                cutlass::platform::is_same<ElementOutput, uint8_t>::value,
                "ElementOutput needs to be 4 or 8 bit (unsigned) int.");
```

Thanks in advance!
