### ISSUE TITLE
cutlass fails to build w/ nvcc unless -std=c++11 is set in NVCC_FLAGS

### ISSUE THREAD

**Issue by Artem-B** [NVIDIA/cutlass#12]
CUTLASS fails to build with default compiler options and CUDA-9.2, where NVCC defaults to -std=c++14. Build works if compiled with -std=c++11.

> /usr/local/google/home/tra/work/cuda/cutlass-1.0/cutlass/util/platform.h(310): error: namespace "std" has no member "bool_constant"

std::bool_constant should be available since C++11, so it's somewhat puzzling that the build works in c++11 mode, but not in c++14.

Reproduction:
System running recent debian distribution.
$ git clone https://github.com/NVIDIA/cutlass.git cutlass-1.0
$ mkdir cutlass-1.0/build
$ cd cutlass-1.0/build
$ cmake -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.2 .. 
$ make VERBOSE=1
<compilation fails>

Full build log: https://pastebin.com/i9VmjZGV

**Comment by jdemouth** [comment]
Hi Artem - Thanks for reporting that issue. We are working on a patch for CUTLASS 1.0 that we are going to release in a few weeks (say around mid-June; but exact date may change) and we'll include a fix for that issue.

**Comment by kerrmudgeon** [comment]
Thank you, Artem. This should be fixed now in CUTLASS 2.0. Closing issue.
