### PR TITLE
fix cinttypes issue with STDC_FORMAT_MACROS

### LINKED ISSUE #1066: [BUG] Compile error with cutlass 3.1.0
**Describe the bug**
Build fails (when compiling flash-attention) with:

```
FAILED: /mnt/ml/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/flash_bwd_hdim128_fp16_sm80.o      
/home/tmm1/micromamba/envs/dev/bin/nvcc  -I/mnt/ml/flash-attention/csrc/flash_attn -I/mnt/ml/flash-attention/csrc/flash_attn/src -I/mnt/ml/flash-attention/csrc/cutlass/include -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include/TH -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include/THC -I/home/tmm1/micromamba/envs/dev/include -I/home/tmm1/micromamba/envs/dev/include/python3.10 -c -c /mnt/ml/flash-attention/csrc/flash_attn/src/flash_bwd_hdim128_fp16_sm80.cu -o /mnt/ml/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/flash_bwd_hdim128_fp16_sm80.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=0

/mnt/ml/flash-attention/csrc/cutlass/include/cute/arch/mma_sm90_desc.hpp(126): error: expected a ")" 
```

**Steps/Code to reproduce bug**
Build on Ubuntu 22.04.03, clone https://github.com/Dao-AILab/flash-attention and run `python setup.py build`

**Expected behavior**
Successful build

**Environment details (please complete the following information):**
 - Environment location: Local bare metal
 - `gcc version 11.4.0 (conda-forge gcc 11.4.0-0)`
 - `Python 3.10.12`

**Additional context**
https://github.com/NVIDIA/cutlass/blob/main/include/cute/arch/mma_sm90_desc.hpp#L147C37-L147C43
cc https://github.com/Dao-AILab/flash-attention/issues/485

### PR DESCRIPTION
**Pull request by tmm1**
closes #1066

cc @thakkarV @mhoemmen

### CODE REVIEW

**Review by hwu36 — APPROVED** [review]

**Comment by tmm1** [comment]
Thanks @hwu36, I'm too used to writing C
