### ISSUE TITLE
[BUG] Compile error with cutlass 3.1.0

### ISSUE THREAD

**Issue by tmm1** [NVIDIA/cutlass#1066]
**Describe the bug**
Build fails (when compiling flash-attention) with:

```
FAILED: /mnt/ml/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/flash_bwd_hdim128_fp16_sm80.o      
/home/tmm1/micromamba/envs/dev/bin/nvcc  -I/mnt/ml/flash-attention/csrc/flash_attn -I/mnt/ml/flash-attention/csrc/flash_attn/src -I/mnt/ml/flash-attention/csrc/cutlass/include -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include/TH -I/home/tmm1/micromamba/envs/dev/lib/python3.10/site-packages/torch/include/THC -I/home/tmm1/micromamba/envs/dev/include -I/home/tmm1/micromamba/envs/dev/include/python3.10 -c -c /mnt/ml/flash-attention/csrc/flash_attn/src/flash_bwd_hdim128_fp16_sm80.cu -o /mnt/ml/flash-attention/build/temp.linux-x86_64-cpython-310/csrc/flash_attn/src/flash_bwd_hdim128_fp16_sm80.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -U__CUDA_NO_BFLOAT16_CONVERSIONS__ --expt-relaxed-constexpr --expt-extended-lambda --use_fast_math --ptxas-options=-v -lineinfo -gencode arch=compute_80,code=sm_80 -gencode arch=compute_90,code=sm_90 --threads 4 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=flash_attn_2_cuda -D_GLIBCXX_USE_CXX11_ABI=0

/mnt/ml/flash-attention/csrc/cutlass/include/cute/arch/mma_sm90_desc.hpp(126): error: expected a ")" 
```

**Steps/Code to reproduce bug**
Build on Ubuntu 22.04.03, clone https://github.com/Dao-AILab/flash-attention and run `python setup.py build`

**Expected behavior**
Successful build

**Environment details (please complete the following information):**
 - Environment location: Local bare metal
 - `gcc version 11.4.0 (conda-forge gcc 11.4.0-0)`
 - `Python 3.10.12`

**Additional context**
https://github.com/NVIDIA/cutlass/blob/main/include/cute/arch/mma_sm90_desc.hpp#L147C37-L147C43
cc https://github.com/Dao-AILab/flash-attention/issues/485

**Comment by tmm1** [comment]
It seems `__STDC_FORMAT_MACROS` is not defined when `inttypes.h` is pulled in. I'm not quite sure why because I do see the g++ 11.4 cinttypes include will set it..

**Comment by thakkarV** [comment]
Which CUDA toolking are you using?

**Comment by tmm1** [comment]
I used micromamba to create the env, as follows. The same behavior happened on another machine with a fresh setup using these same instructions:

```
micromamba create -n dev python=3.10 -c conda-forge
micromamba activate dev
micromamba install gcc=11.4.0 gxx=11.4.0 -c conda-forge
micromamba install cuda-toolkit -c nvidia/label/cuda-11.8.0
```

**Comment by thakkarV** [comment]
CC @mhoemmen

**Comment by mhoemmen** [comment]
@thakkarV This is probably an easy fix by casting to `long long` and using `%LLi` instead of the cinttypes macro (alas).

**Comment by tmm1** [comment]
I agree that seems like the simplest fix. I am happy to put together a PR.

**Comment by mhoemmen** [comment]
Thanks for the fix! : - )
